config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    resources :posts
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
# ApplicationHelper provides helper methods for views.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# ApplicationHelper provides helper methods for views.
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  alias_attribute :author, :user

  validates :author, presence: true
  validates :text, presence: true
end

app/models/like.rb
# ApplicationHelper provides helper methods for views.
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user, uniqueness: { scope: :post }
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_default_counters
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes
  has_many :comments

  # title must not be blank
  validates :title, presence: true

  # title must not exceed 250 characters
  validates :title, length: { maximum: 250 }

  # CommentsCounter must be an integer greater than or equal to zero
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # LikesCounter must be an integer greater than or equal to zero
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def set_default_counters
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
# ApplicationHelper provides helper methods for views.
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# ApplicationHelper provides helper methods for views.
module ApplicationHelper
  # Add your helper methods here
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
# UsersHelper provides helper methods for views.
module UsersHelper
end

app/views/comments/new.html.erb
<h3 style="color: #336699; margin: 12px 50px">Create a new comment💬</h3>
<%= form_with model: [@user, @post, @comment], url: user_post_comments_path(@post.author, @post), method: :post do |f| %>
  <div class="inputs">
    <%= f.label :text, style: "font-weight: bold;" %>
    <%= f.text_area :text, style: "width: 230px; height: 80px; padding: 10px" %>
  </div>
  <div>
    <%= f.submit "Submit the comment💬", style: "background-color: #007BFF; margin: 10px 100px; color: #fff; padding: 10px 15px; border: none; border-radius: 5px;" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<h3 style="color: #336699; margin: 12px">If you Like the post just Click the button 👍😍</h3>
<%= form_with model: [@user, @post, @like], url: user_post_likes_path(@user, @post), method: :post do |f| %>
  <div>
    <%= f.submit "👍 Like", style: "background-color: #007BFF; margin: 10px 110px; color: #fff; padding: 10px 15px; border: none; border-radius: 5px; cursor: pointer;" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="user_info">
    <div class="img">
      <%= image_tag @user.photo, alt: "User Photo", class: "user-photo" %>
    </div>
    <div class="user">
      <h2><%= link_to @user.name, user_path(@user) %></h2>
      <p><strong>Number of Posts:</strong> <%= @user.posts.count %></p>
    </div>
  </div>

  <% @posts.limit(2).each do |post| %>
    <div class="post">
      <h4>Post</h4>
      <p><%= post.text %></p>
      <p class="count">Comments: <%= post.comments.count %> | Likes: <%= post.likes.count %></p>
    </div>
      <div class="comments">
        <% post.five_most_recent_comments.each do |comment| %>
          <div class="comment">
            <p><%= link_to comment.author.name, user_path(comment.author) %>: <%= comment.text %></p>
          </div>
        <% end %>
      </div>
  <% end %>

  <%= link_to 'Pagination', user_posts_path(@user), class: 'button' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post">
    <h4>Post <%= @post.title %></h4>
    <p class="count">Comments: <%= @post.comments.count %> | Likes: <%= @post.likes.count %></p>
    <p><%= @post.text %></p>
  </div>

  <div class="comments">
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <p><%= comment.author.name %>: <%= comment.text %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<% @users.each do |user| %>
  <div class="user_info">
    <div class="img">
    <%= image_tag user.photo, alt: "User Photo", class: "user-photo"%>
  </div>
  <div class="user">
    <h2><%= link_to user.name, user_path(user) %></h2>
    <p><strong>Number of Posts:</strong> <%= user.posts.count %></p>
  </div>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user_info">
    <div class="img">
      <%= image_tag @user.photo, alt: "User Photo", class: "user-photo"%>
    </div>
    <div class="user">
      <h2><%= @user.name %></h2>
      <p><strong>Number of Posts:</strong> <%= @user.posts.count %></p>
    </div>
  </div>
  <div class="user_bio">
    <p>Bio</p>
  <p><%= @user.bio %></p>
  </div>
  <% @user.three_recent_posts.each_with_index do |post, index| %>
  <div class="post">
    <h4>Post <%= index+1  %>: <%= link_to post.title, user_post_path(@user, post) %></h4>
    <p><%= post.text %></p>
    <p class="count">Comments: <%= post.comments.count %> | Likes: <%= post.likes.count %></p>
  </div>
<% end %>
  <%= link_to "See all posts", user_posts_path(@user), class: 'button' %>
</div>